version: 2.1

jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - run:
          name: Run build
          command: pnpm nx run-many -t build

workflows:
  version: 2
  ci:
    jobs:
      - main
